http://code.google.com/p/mb-unit/issues/detail?id=6
1. If resource file doesn't exist, an error is generated but parsing and running the tests continues.
 - MSBuild in this case stops with error message.
      MSBUILD : error MSB1022: Response file does not exist.
      Switch: @response.rsp
 - Code was modified to follow MsBuild example. Now similar message
   is going to be displayed:
      ERROR: Response file does not exist.
      Switch: @responseFile